#! /bin/bash
#    Copyright (c) 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#This runs a graphical terminal full screen to connect to the socat socket
set -m

UvTTYName=$1
if [[ -z $UvTTYName ]]
then
  echo "Incorrect arguments passed"
  exit 1
fi

#Use bash builtin sleep if availible
if [[ -f /usr/lib/bash/sleep ]]
then
  enable -f /usr/lib/bash/sleep sleep
  SLEEPCMD=\sleep
else
  SLEEPCMD=/bin/sleep
fi


while [ 1 ]
do
  tail --follow=name "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/uvttysuspend" &> /dev/null

  cage -m last -d -s -- \
  foot --font DejaVuSansMono:size=11 -- \
  /usr/libexec/uvtty/uvtty-fe-connect $UvTTYName &
  CAGEPID=$!

  mkdir -p "$XDG_RUNTIME_DIR/uvtty/$UvTTYName"
  echo $CAGEPID > "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/cagepid" 2>/dev/null
  if [[ -e /proc/$CAGEPID ]]
  then
    fg 1
  fi

  rm "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/cagepid" &>/dev/null

  $SLEEPCMD 1
  if [[ ! -e "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/socatproxy" ]]
  then
    exit
  fi

done
