#! /bin/bash
#    Copyright (c) 2012 - 2026 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#This runs a graphical terminal full screen to connect to the socat socket

function GetFirstSeatCard
{
  MatchSeat=$XDG_SEAT
  if [[ -z $XDG_SEAT ]]
  then
    MatchSeat=seat0
  fi

  SeatCardFound=0
  SelectCard=""
  while read -r ReadCard
  do
    ReadCardSeat=$(udevadm info --query=property  --property ID_SEAT --value --name=$ReadCard)
    CardIsVGABoot=$(udevadm info --name=$ReadCard -a | grep -c "{boot_vga}")
    if [[ -z $ReadCardSeat ]]
    then
      ReadCardSeat=seat0
    fi

    if [[ $ReadCardSeat == $MatchSeat ]]
    then
      SeatCardFound=1
      SelectCard=$ReadCard
      if [[ $CardIsVGABoot -gt 0 ]]
      then
        break
      fi
    fi
  done < <(ls -r /dev/dri/card*)
  if [[ $SeatCardFound != 0 ]]
  then
    echo $SelectCard
  fi
}

function UvTTYFrontendMain
{
  set -m

  UvTTYName=$1
  if [[ -z $UvTTYName ]]
  then
    echo "Incorrect arguments passed"
    exit 1
  fi

  #Use bash builtin sleep if availible
  if [[ -f /usr/lib/bash/sleep ]]
  then
    enable -f /usr/lib/bash/sleep sleep
    SLEEPCMD="sleep"
  else
    SLEEPCMD="/bin/sleep"
  fi

  LoopStartTime=$EPOCHSECONDS
  AttemptItr=0
  while ((AttemptItr < 5))
  do
    if [[ -e "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/uvttysuspend" ]]
    then
      AttemptItr=0
      tail --follow=name "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/uvttysuspend" &> /dev/null
    fi

    #Prefer the user's .config/uvtty/footkiosk.conf if it exists
    if [[ -e "$HOME/.config/uvtty/footkiosk.conf" ]]
    then
      FOOT_CONFIG_FILE="$HOME/.config/uvtty/footkiosk.conf"
    else
      FOOT_CONFIG_FILE="/etc/vtty/footkiosk.conf"
    fi

    #Get the keyboard layout from /etc/vconsole.conf or .config
    #Existing keymaps, options, variants, and models only have numbers, letters, hyphens, underscores and colons.
    XKBLAYOUT=""
    XKBMODEL=""
    XKBVARIANT=""
    XKBOPTIONS=""

    #Prefer the user's .config/uvtty/vconsole.conf if it exists
    if [[ -e "$HOME/.config/uvtty/vconsole.conf" ]]
    then
      VCONSOLE_CONFIG_FILE="$HOME/.config/uvtty/vconsole.conf"
    else
      VCONSOLE_CONFIG_FILE="/etc/vconsole.conf"
    fi

    while read -r LINE
    do
      Name=$(echo "$LINE" | awk -F '=' '{print $1}')
      Value=$(echo "$LINE" | awk -F '=' '{print $2}')

      export "$Name"="$Value"
    done < <(cat "$VCONSOLE_CONFIG_FILE" | sed 's/[^#=:a-zA-Z0-9_-]//g'| grep -vE '^$|#')

    #Allow kernel command line options vconsole.xkblayout=, vconsole.xkbmodel=, vconsole.xkbvariant=, and vconsole.xkboptions= to take precidence
    readarray -d " " KernelCommandLineOptions < /proc/cmdline
    for KernelCommandLineOption in "${KernelCommandLineOptions[@]}"
    do
      if [[ $KernelCommandLineOption == vconsole.xkblayout=* ]]
      then
        XKBLAYOUT=${KernelCommandLineOption/vconsole.xkblayout=/}

      elif [[ $KernelCommandLineOption == vconsole.xkbmodel=* ]]
      then
        XKBMODEL=${KernelCommandLineOption/vconsole.xkbmodel=/}

      elif [[ $KernelCommandLineOption == vconsole.xkbvariant=* ]]
      then
        XKBVARIANT=${KernelCommandLineOption/vconsole.xkbvariant=/}

      elif [[ $KernelCommandLineOption == vconsole.xkboptions=* ]]
      then
        XKBOPTIONS=${KernelCommandLineOption/vconsole.xkboptions=/}

      fi
    done

    export XKB_DEFAULT_LAYOUT=$XKBLAYOUT
    export XKB_DEFAULT_MODEL=$XKBMODEL
    export XKB_DEFAULT_VARIANT=$XKBVARIANT
    export XKB_DEFAULT_OPTIONS=$XKBOPTIONS

    #Workaround for https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/4040
    export WLR_DRM_DEVICES=$(GetFirstSeatCard)

    cage -d -s -- \
    foot --config="$FOOT_CONFIG_FILE" -- \
    /usr/libexec/uvtty/uvtty-fe-connect $UvTTYName &
    CAGEPID=$!

    mkdir -p "$XDG_RUNTIME_DIR/uvtty/$UvTTYName"
    echo $CAGEPID > "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/cagepid" 2>/dev/null
    if [[ -e /proc/$CAGEPID ]]
    then
      fg 1
    fi

    rm "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/cagepid" &>/dev/null

    if [[ ! -e "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/socatproxy" ]]
    then
      #Force the backend proxy command loop to run so the bash trap detects the process exiting sooner
      if [[ -e $XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptycommandproxy ]]
      then
        echo "" > $XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptycommandproxy
      fi
      exit
    fi
    $SLEEPCMD 1

    ((AttemptItr++))

    if [[ $AttemptItr -ge 5 ]]
    then
      LoopStartDelay=$(($EPOCHSECONDS - $LoopStartTime))
      if [[ $LoopStartDelay -gt 60 ]]
      then
        AttemptItr=0
        LoopStartTime=$EPOCHSECONDS
      fi
    fi
  done

  #If the loop breaks, something went wrong, abort the session
  loginctl terminate-session $XDG_SESSION_ID

  exit
}

UvTTYFrontendMain "$@"
