#! /bin/bash
#    Copyright (c) 2012 - 2022 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#This runs the shell, and links the current PTY
UvTTYName=$1
if [[ -z $UvTTYName ]]
then
  echo "Incorrect arguments passed"
  exit 1
fi

shift
export TERM=xterm-256color
unset WAYLAND_DISPLAY

#Create a static name for the PTY that this is running as
PTYPath=$(tty)
IFS="/"
PTYPathArray=($PTYPath)
unset IFS
PTYNumber=${PTYPathArray[-1]}

if [[ -e "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptylink" ]]
then
  rm "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptylink"
fi
ln -s $PTYPath "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptylink"

"$@"

rm "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptylink" &>/dev/null
pkill $SOCAT_PID
exit $?
