#! /bin/bash
#    Copyright (c) 2012 - 2025 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

function GetFirstSeatCard
{
  MatchSeat=$XDG_SEAT
  if [[ -z $XDG_SEAT ]]
  then
    MatchSeat=seat0
  fi

  SeatCardFound=0
  SelectCard=""
  while read -r ReadCard
  do
    ReadCardSeat=$(udevadm info --query=property  --property ID_SEAT --value --name=$ReadCard)
    CardIsVGABoot=$(udevadm info --name=$ReadCard -a | grep -c "{boot_vga}")
    if [[ -z $ReadCardSeat ]]
    then
      ReadCardSeat=seat0
    fi

    if [[ $ReadCardSeat == $MatchSeat ]]
    then
      SeatCardFound=1
      SelectCard=$ReadCard
      if [[ $CardIsVGABoot -gt 0 ]]
      then
        break
      fi
    fi
  done < <(ls -r /dev/dri/card*)
  if [[ $SeatCardFound != 0 ]]
  then
    echo $SelectCard
  fi
}

function UvTTYSessionMain
{
  export XDG_CURRENT_DESKTOP=UvTTY
  export WLR_BACKENDS=libinput,drm
  export WLR_RENDERER_ALLOW_SOFTWARE=1
  export WLR_DRM_DEVICES=$(GetFirstSeatCard)
  export WLR_RENDERER=pixman
  export WLR_NO_HARDWARE_CURSORS=1
  export WLR_LIBINPUT_NO_DEVICES=1

  UvTTYName="${XDG_SEAT}-${XDG_SESSION_ID}"

  #Make the proxy folder
  mkdir -p "$XDG_RUNTIME_DIR/uvtty/$UvTTYName"

  #Fall back if the seat name pushes the name longer than a the max file name length
  if [[ ${#UvTTYName} -ge 255 ]]
  then
    UvTTYName=$RANDOM
  fi
  export UvTTYName=$UvTTYName

  #Create the FIFO to where resize commands will be sent
  if [[ -e "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptycommandproxy" ]]
  then
    rm "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptycommandproxy"
  fi
  mkfifo -m 600 "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/ptycommandproxy"

  /usr/libexec/uvtty/uvtty-frontend $UvTTYName &
  /usr/libexec/uvtty/uvtty-backend $UvTTYName
  exit
}

UvTTYSessionMain "$@"
