#! /bin/bash
#    Copyright (c) 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Require root privlages
if [[ $UID != 0 ]]
then
  echo "Must be run as root."
  exit
fi

patch /usr/bin/waylandloginmanager /usr/share/RBOS_PATCHES/waylandloginmanagerkdialog.diff  -t --no-backup-if-mismatch --dry-run

if [[ $? == 0 ]]
then
  patch /usr/bin/waylandloginmanager /usr/share/RBOS_PATCHES/waylandloginmanagerkdialog.diff  -t --no-backup-if-mismatch
fi
systemctl restart waylandloginmanager.service
