#! /bin/bash
#    Copyright (c) 2012 - 2024 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

function call_program
{
  for (( launch_count=0 ; launch_count < 5 ; launch_count++ ))
  do
    "$@"
  done
}

function launch_watcher
{
   call_program "$@" &
}

if [[ $LABWC_AUTOLAUNCH == "XFCE" ]]
then
  launch_watcher xfdesktop
  launch_watcher xfce4-panel
fi

if [[ $LABWC_AUTOLAUNCH == "LXQt" ]]
then
  launch_watcher pcmanfm-qt --desktop
  launch_watcher lxqt-session
fi
