#! /bin/bash
#    Copyright (c) 2012 - 2026 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#This handles the connection to the main pty running login, (this is run within the terminal emulator)

function PtyResizeEvent
{
  if [[ ! -e /run/vtty/$EmulatedTTY/ptycommandproxy ]]
  then
    Retries=0
    while [[ ! -e /run/vtty/$EmulatedTTY/ptycommandproxy ]]
    do
      $SLEEPCMD 1
      ((Retries++))
      if [[ $Retries -ge 5 ]]
      then
        return
      fi
    done
  fi

  #Wait for the terminal client to act when SIG_WINCH is sent before getting the size
  $SLEEPCMD .3
  ClientPTYSize=($(stty size))
  echo "s ${ClientPTYSize[0]} ${ClientPTYSize[1]}" > /run/vtty/$EmulatedTTY/ptycommandproxy
}

function vTTYFeConnectMain
{
  EmulatedTTY=$1
  PTYPath=$(tty)

  #Use bash builtin sleep if availible
  if [[ -f /usr/lib/bash/sleep ]]
  then
    enable -f /usr/lib/bash/sleep sleep
    SLEEPCMD="sleep"
  else
    SLEEPCMD="/bin/sleep"
  fi

  if [[ -e /run/vtty/$EmulatedTTY/waylandserver ]]
  then
    rm /run/vtty/$EmulatedTTY/waylandserver
  fi
  ln -s $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY /run/vtty/$EmulatedTTY/waylandserver

  socat file:$PTYPath,raw,echo=0 unix-connect:/run/vtty/$EmulatedTTY/socatproxy &

  #Resize events will be rare (it's fullscreen), but probably possible if a screen is swapped
  trap PtyResizeEvent WINCH
  PtyResizeEvent

  while [ 1 ]
  do
    wait $!
    $SLEEPCMD .1
  done

  exit
}

vTTYFeConnectMain "$@"
