#! /bin/bash
#    Copyright (c) 2012 - 2023 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#This handles the login prompt and handling of /etc/issue

EmulatedTTY=$1

#Use bash builtin sleep if availible
if [[ -f /usr/lib/bash/sleep ]]
then
  enable -f /usr/lib/bash/sleep sleep
  SLEEPCMD=\sleep
else
  SLEEPCMD=/bin/sleep
fi

#Create a static name for the PTY that this is running as
PTYPath=$(tty)
IFS="/"
PTYPathArray=($PTYPath)
unset IFS
PTYNumber=${PTYPathArray[-1]}

if [[ -e /run/vtty/$EmulatedTTY/loginpty ]]
then
  rm /run/vtty/$EmulatedTTY/loginpty
fi
ln -s $PTYPath /run/vtty/$EmulatedTTY/loginpty


function DoLoginPrompt
{
  export TERM=xterm-256color
  tput reset
  tput clear

  unset NOTIFY_SOCKET
  unset INVOCATION_ID
  unset JOURNAL_STREAM
  export VTTY=$EmulatedTTY
  echo "v${VTTY} backed by $PTYPath"

  #Clear the clipboard
  if [[ -e /run/vtty/$EmulatedTTY/waylandserver ]]
  then
    WAYLAND_DISPLAY=/run/vtty/$EmulatedTTY/waylandserver /opt/bin/wl-copy ""
  fi

  #/usr/bin/vtty-login-program could be a symlink provided by another package, such as console-conf
  VTTY_LOGIN_PROGRAM=$(command -v vtty-login-program)
  if [[ ! -z $VTTY_LOGIN_PROGRAM ]]
  then
    env -i COLORTERM=truecolor XDG_SEAT=seat-vtty TERM=$TERM VTTY=$VTTY setsid /sbin/agetty -n --noclear -l $VTTY_LOGIN_PROGRAM pts/$PTYNumber $TERM
  else
    env -i COLORTERM=truecolor XDG_SEAT=seat-vtty TERM=$TERM VTTY=$VTTY setsid /sbin/agetty -o '-p -- \u' --noclear --keep-baud --nonewline pts/$PTYNumber $TERM
  fi
}

trap 'DoLoginPrompt' 2

while [ 1 ]
do
  DoLoginPrompt
  if [[ ! -e $PTYPath ]]
  then
    exit 1
  fi
  $SLEEPCMD .1
done
exit 0
