#!/bin/sh

PREREQ="udev"
prereqs()
{
        echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

#if [ ! -e /dev/dri/card0 ]
#then
#	modprobe simpledrm
#fi

#cmdlinecount=$(grep -c '\bsimpledrm.forceload\b' /proc/cmdline)
#if [ $cmdlinecount -gt 0 ]
#then
#	modprobe simpledrm
#fi
