#! /bin/bash
#    Copyright (c) 2012 - 2026 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

NewFileName=weston-wcap
FileNumber=1
if [[ -e ~/weston-screenshots/"$NewFileName".webm ]]
then
  while [[ -e ~/weston-screenshots/$NewFileName-$FileNumber.webm ]]
  do
    ((FileNumber++))
  done
  NewFileName=$NewFileName-$FileNumber.webm
else 
  NewFileName=weston-wcap.webm
fi

#Decode weston's wcap files
if [[ -e ~/capture.wcap ]]
then
  wcap-decode  --yuv4mpeg2 ~/capture.wcap | vpxenc --target-bitrate=1024 --best -t 4 -o ~/weston-screenshots/$NewFileName - --codec=vp8
  mv ~/capture.wcap ~/weston-screenshots/$(date +%s)capture.wcap
fi
