#! /bin/bash
#    Copyright (c) 2012 - 2023 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#This script manages the Weston instance that acts as the proxy for Weston screen sharing

/opt/bin/weston --no-config --xwayland --backend=rdp-backend.so --shell=fullscreen-shell.so --rdp-tls-cert=./.config/weston-rdp/HOST.crt --rdp-tls-key=./.config/weston-rdp/HOST.key & WESTONPID=$!
/usr/libexec/weston_helpers/rdpdialog $WAYLAND_DISPLAY &
DIALOGPID=$!
while [ 1 ]
do
  if [ ! -e /proc/$DIALOGPID -o ! -e /proc/$WESTONPID ]
  then
    kill -9 $WESTONPID
    kill -9 $DIALOGPID
    exit
  fi
  sleep 1
done
