#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions


sed -i 's|export PATH=|export PATH=/opt/bin:/opt/sbin:|' "${DESTDIR}/init"
