#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules evdev

if [ -z "$LOCALE_LIB_DIR" ]
then
  LOCALE_LIB_DIR=/usr/lib/locale
fi

if [ -z "$LIBINPUT_SHARE_DIR" ]
then
  LIBINPUT_SHARE_DIR=/usr/share/libinput
fi

if [ -z "$LIBX11_SHARE_DIR" ]
then
  LIBX11_SHARE_DIR=/usr/share/X11
fi

copy_exec "$(which cage)" /usr/bin/
copy_exec "$(which foot)" /usr/bin/
copy_exec "$(which id)" /usr/bin/
copy_exec "$(which wlr-randr)" /usr/bin/
copy_exec "$(which tput)" /usr/bin/

if [ -e "/usr/bin/recinit" ]
then
  copy_file script "/usr/bin/recinit"
fi

mkdir -p "${DESTDIR}/lib/udev/rules.d"
cp /lib/udev/rules.d/60-input-id.rules "${DESTDIR}/lib/udev/rules.d"

MonospaceFontPath=$(fc-match -f %{file} monospace)
if [ -n "$MonospaceFontPath" ]
then
  MonospaceFontFolder=$(dirname "$MonospaceFontPath")
  mkdir -p "${DESTDIR}/$MonospaceFontFolder"
  cp -a "$MonospaceFontPath" "${DESTDIR}/$MonospaceFontFolder"
fi

BoldMonospaceFontPath=$(fc-match -f %{file} monospace:weight=bold)
if [ -n "$BoldMonospaceFontPath" ]
then
  BoldMonospaceFontFolder=$(dirname "$BoldMonospaceFontPath")
  mkdir -p "${DESTDIR}/$BoldMonospaceFontFolder"
  cp -a "$BoldMonospaceFontPath" "${DESTDIR}/$BoldMonospaceFontFolder"
fi

if [ -e "$LOCALE_LIB_DIR"/[cC].[uU][tT][fF]*8/ ]
then
  CUTF8DIR=$(basename $(ls -d "$LOCALE_LIB_DIR"/[cC].[uU][tT][fF]*8))
  mkdir -p "${DESTDIR}/$LOCALE_LIB_DIR/$CUTF8DIR/"
  cp -a "$LOCALE_LIB_DIR/$CUTF8DIR/"* "${DESTDIR}/$LOCALE_LIB_DIR/$CUTF8DIR/"
fi

if [ -e "$LIBINPUT_SHARE_DIR" ]
then
  mkdir -p "${DESTDIR}/$LIBINPUT_SHARE_DIR/"
  cp -a "$LIBINPUT_SHARE_DIR"/* "${DESTDIR}/$LIBINPUT_SHARE_DIR/"
fi

if [ -e "$LIBX11_SHARE_DIR/xkb" ]
then
  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/"
  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"

  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/keycodes/"
  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/rules/"
  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/symbols/"
  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/accessx" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/basic" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/caps" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/complete" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/iso9995" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/ledcaps" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/lednum" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/ledscroll" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/level5" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/misc" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/mousekeys" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/compat/xfree86" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/compat/"
  cp "$LIBX11_SHARE_DIR/xkb/keycodes/aliases" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/keycodes/"
  cp "$LIBX11_SHARE_DIR/xkb/keycodes/evdev" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/keycodes/"
  cp "$LIBX11_SHARE_DIR/xkb/rules/evdev" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/rules/"
  find "$LIBX11_SHARE_DIR/xkb/symbols" -maxdepth 1 ! -type d | while read -r file
  do
    cp "$file" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/symbols/"
  done
  cp "$LIBX11_SHARE_DIR/xkb/types/basic" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/complete" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/extra" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/iso9995" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/level5" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/mousekeys" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/numpad" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
  cp "$LIBX11_SHARE_DIR/xkb/types/pc" "${DESTDIR}/$LIBX11_SHARE_DIR/xkb/types/"
fi

if [ -e "$LIBX11_SHARE_DIR/locale" ]
then
  mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/locale/"
  # In the off chance the user uses their compose key in initrd
  if [ -f "$LIBX11_SHARE_DIR/locale/compose.dir" ]
  then
    cp "$LIBX11_SHARE_DIR/locale/compose.dir" "${DESTDIR}/$LIBX11_SHARE_DIR/locale/"
    grep UTF-8/Compose: "$LIBX11_SHARE_DIR/locale/compose.dir" | awk -F: '{ print $1 }' | sort -u | xargs dirname | while read -r DIR
    do
      mkdir -p "${DESTDIR}/$LIBX11_SHARE_DIR/locale/$DIR"
      find "$LIBX11_SHARE_DIR/locale/$DIR" -maxdepth 1 ! -type d | while read -r file
      do
        cp "$file" "${DESTDIR}/$LIBX11_SHARE_DIR/locale/$DIR"
      done
    done
  fi
fi

if [ -e "/etc/vtty" ]
then
  mkdir -p "${DESTDIR}/etc/vtty"
  cp -a "/etc/vtty"/* "${DESTDIR}/etc/vtty"
fi

echo ". /scripts/override/panic" >> "${DESTDIR}/scripts/functions"
