#! /bin/bash
#    Copyright (c) 2012 - 2025 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

mkdir -p /var/lib/divert-distrib

#2 arguments: The first argument is the file to redirect, the second argument is where to redirect the file to
function DivertDpkgFile
{
  SourceFile="$1"
  DivertDestination="$2"

  DivertPackage=$(dpkg-divert --listpackage "$SourceFile")
  if [[ "$DivertPackage" != "$DPKG_MAINTSCRIPT_PACKAGE" ]]
  then
    dpkg-divert --package "$DPKG_MAINTSCRIPT_PACKAGE" --add --rename --divert "$DivertDestination" "$SourceFile"
  fi
}

DivertDpkgFile /etc/skel/.bashrc           /var/lib/divert-distrib/etc_skel_.bashrc
DivertDpkgFile /etc/issue                  /var/lib/divert-distrib/etc_issue
DivertDpkgFile /etc/issue.net              /var/lib/divert-distrib/etc_issue.net
DivertDpkgFile /etc/os-release             /var/lib/divert-distrib/etc_os-release
DivertDpkgFile /etc/lsb-release            /var/lib/divert-distrib/etc_lsb-release
DivertDpkgFile /usr/bin/X                  /var/lib/divert-distrib/usr_bin_X
DivertDpkgFile /usr/bin/plymouth           /var/lib/divert-distrib/usr_bin_plymouth
DivertDpkgFile /usr/bin/chvt               /var/lib/divert-distrib/usr_bin_chvt
DivertDpkgFile /usr/lib/os-release         /var/lib/divert-distrib/usr_lib_os-release
