#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring journald..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

echo "Storage=none" >> /root/etc/systemd/journald.conf

log_end_msg 
