#! /bin/bash
#    Copyright (c) 2012 - 2024 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

SelectedISO="$1"
MaxProcs=$(nproc)
DefaultCPUCount=$((MaxProcs/2))
if [[ $DefaultCPUCount == 0 ]]
then
  DefaultCPUCount=1
fi

MaxRAM=$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1024))
DefaultRAM=$((MaxRAM/5))

#Detect installed dialog programs
if [[ -f $(which kdialog) ]]
then
  HASKDIALOG=1
else
  HASKDIALOG=0
fi

if [[ -f $(which zenity) ]]
then
  HASZENITY=1
else
  HASZENITY=0
fi

if [[ -f $(which dialog) ]]
then
  HASDIALOG=1
else
  HASDIALOG=0
fi

#Determine what dialog program to use
if [[ $HASZENITY == 1 ]]
then
  UIDIALOGTYPE=zenity
elif [[ $HASKDIALOG == 1 ]]
then
  UIDIALOGTYPE=kdialog
elif [[ $HASDIALOG == 1 ]]
then
  UIDIALOGTYPE=dialog
else
  UIDIALOGTYPE=none
fi

if [[ -z $SelectedISO ]]
then
  if [[ $UIDIALOGTYPE == kdialog ]]
  then
    SelectedISO=$(kdialog --getopenfilename)
  elif [[ $UIDIALOGTYPE == zenity ]]
  then
    SelectedISO=$(zenity --file-selection)
  elif [[ $UIDIALOGTYPE == dialog ]]
  then
    SelectedISO=$(dialog --fselect $HOME/ 20 60 --stdout)
  elif [[ $UIDIALOGTYPE == none ]]
  then
    echo "No ISO specified as an argument to this script, and no dialog utilites are installed to select one."
    exit 1
  fi
fi

if [[ $UIDIALOGTYPE == kdialog ]]
then
  SelectedCPUCount=$(kdialog --slider "Number of CPUs (1-$MaxProcs)" 1 $MaxProcs $MaxProcs)
elif [[ $UIDIALOGTYPE == zenity ]]
then
  SelectedCPUCount=$(zenity --scale --text="Number of CPUs" --min-value=1 --max-value=$MaxProcs --value=$DefaultCPUCount)
elif [[ $UIDIALOGTYPE == dialog ]]
then
  SelectedCPUCount=$(dialog --rangebox "Number of CPUs" 10 40 1 $MaxProcs $DefaultCPUCount --stdout)
elif [[ $UIDIALOGTYPE == none ]]
then
  SelectedCPUCount=$DefaultCPUCount
fi


if [[ $UIDIALOGTYPE == kdialog ]]
then
  SelectedRAMValue=$(kdialog --slider "Amount of RAM in MB (256-$MaxRAM)" 256 $MaxRAM $MaxRAM)
elif [[ $UIDIALOGTYPE == zenity ]]
then
  SelectedRAMValue=$(zenity --scale --text="Amount of RAM in MB" --min-value=256 --max-value=$MaxRAM --value=$DefaultRAM)
elif [[ $UIDIALOGTYPE == dialog ]]
then
  SelectedRAMValue=$(dialog --rangebox "Amount of RAM in MB" 10 40 256 $MaxRAM $DefaultRAM --stdout)
elif [[ $UIDIALOGTYPE == none ]]
then
  SelectedRAMValue=$DefaultRAM
fi


qemu-system-x86_64 -smp $SelectedCPUCount -boot d -m $SelectedRAMValue -cdrom "$SelectedISO" -vga virtio -display gtk -enable-kvm \
-device pci-bridge-seat,chassis_nr=2,id=head.2 \
-device virtio-gpu-pci,bus=head.2,addr=02.0,id=video.2 \
-device virtio-keyboard-pci,bus=head.2,display=video.2 \
-device virtio-tablet-pci,bus=head.2,display=video.2
