#! /bin/bash
#    Copyright (c) 2012 - 2024 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#This utility is for development only, it lists files that built packages may have in /usr instead of /opt that may conflict with ones from any tier 1 pacakage

sudo apt-file update

declare -A FilesToPackage
while read PACKAGEFILE
do
  PACKAGEFILE="${PACKAGEFILE/: /$'\t'}"
  IFS=$'\t'
  PACKAGEFILE=( $PACKAGEFILE )
  unset IFS
  PACKAGE="${PACKAGEFILE[0]}"
  FILE="${PACKAGEFILE[1]}"
  FilesToPackage[$FILE]="$PACKAGE"
done < <(apt-file search --stream-results -x ^ | sed 's| /lib/| /usr/lib/|g' | sed 's| /bin/| /usr/bin/|g')


while read PACKAGE
do
  while read FILE
  do
    if [[ -d $FILE ]]
    then
      continue
    fi
    FILEPACKAGE=${FilesToPackage["$FILE"]}
    if [[ ! -z "$FILEPACKAGE" ]]
    then
      DIVERTPACKAGE=$(dpkg-divert --listpackage "$FILE")
      if [[ ! -z "$DIVERTPACKAGE" ]]
      then
        echo "$PACKAGE conflicts with $FILEPACKAGE with file: $FILE , but $FILE is diverted by $DIVERTPACKAGE"
      else
        echo "$PACKAGE conflicts with $FILEPACKAGE with file: $FILE"
     fi
    fi
  done < <(dpkg -L "$PACKAGE")
done < <(dpkg --get-selections | grep install$ | awk '{print $1}' | grep -- -rbos$)
