#! /bin/bash
#    Copyright (c) 2012 - 2024 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
SCRIPTFILEPATH=$(readlink -f "$0")
SCRIPTFOLDERPATH=$(dirname "$SCRIPTFILEPATH")

jp2a --colors --color-depth=24 $SCRIPTFOLDERPATH/rbos_logo_source.png             > $SCRIPTFOLDERPATH/asciilogos/logo_24_default.txt 
jp2a --colors --color-depth=24 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=32 > $SCRIPTFOLDERPATH/asciilogos/logo_24_32.txt
jp2a --colors --color-depth=24 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=16 > $SCRIPTFOLDERPATH/asciilogos/logo_24_16.txt
jp2a --colors --color-depth=24 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=8  > $SCRIPTFOLDERPATH/asciilogos/logo_24_8.txt

jp2a --colors --color-depth=8 $SCRIPTFOLDERPATH/rbos_logo_source.png             > $SCRIPTFOLDERPATH/asciilogos/logo_8_default.txt 
jp2a --colors --color-depth=8 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=32 > $SCRIPTFOLDERPATH/asciilogos/logo_8_32.txt
jp2a --colors --color-depth=8 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=16 > $SCRIPTFOLDERPATH/asciilogos/logo_8_16.txt
jp2a --colors --color-depth=8 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=8  > $SCRIPTFOLDERPATH/asciilogos/logo_8_8.txt


jp2a --colors --color-depth=4 $SCRIPTFOLDERPATH/rbos_logo_source.png             > $SCRIPTFOLDERPATH/asciilogos/logo_4_default.txt 
jp2a --colors --color-depth=4 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=32 > $SCRIPTFOLDERPATH/asciilogos/logo_4_32.txt
jp2a --colors --color-depth=4 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=16 > $SCRIPTFOLDERPATH/asciilogos/logo_4_16.txt
jp2a --colors --color-depth=4 $SCRIPTFOLDERPATH/rbos_logo_source.png --height=8  > $SCRIPTFOLDERPATH/asciilogos/logo_4_8.txt

jp2a $SCRIPTFOLDERPATH/rbos_logo_source.png             > $SCRIPTFOLDERPATH/asciilogos/logo_0_default.txt 
jp2a $SCRIPTFOLDERPATH/rbos_logo_source.png --height=32 > $SCRIPTFOLDERPATH/asciilogos/logo_0_32.txt
jp2a $SCRIPTFOLDERPATH/rbos_logo_source.png --height=16 > $SCRIPTFOLDERPATH/asciilogos/logo_0_16.txt
jp2a $SCRIPTFOLDERPATH/rbos_logo_source.png --height=8  > $SCRIPTFOLDERPATH/asciilogos/logo_0_8.txt

