#! /bin/bash
#    Copyright (c) 2012 - 2024 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
SCRIPTFILEPATH=$(readlink -f "$0")
SCRIPTFOLDERPATH=$(dirname "$SCRIPTFILEPATH")

#https://stackoverflow.com/questions/10918907/how-to-add-transparent-watermark-in-center-of-a-video-with-ffmpeg
#https://stackoverflow.com/questions/71910384/ffmpeg-removing-black-outline-on-overlay-after-alphamerge

ffmpeg -i "$SCRIPTFOLDERPATH"/wallpaper_login.png -i "$SCRIPTFOLDERPATH"/rbos_logo_boot.png -filter_complex "[1] unpremultiply=inplace=1 [front]; [0] [front] overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2:format=rgb" -map 0:a?  -y "$SCRIPTFOLDERPATH"/../../rebeccablackos_files/usr/share/wallpapers/RBOS_Login/contents/images/1920x1200.png

ffmpeg -i "$SCRIPTFOLDERPATH"/wallpaper_desktop.png -i "$SCRIPTFOLDERPATH"/rbos_logo_boot.png -filter_complex "[1] unpremultiply=inplace=1 [front]; [0] [front] overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2:format=rgb" -map 0:a?  -y "$SCRIPTFOLDERPATH"/../../rebeccablackos_files/usr/share/wallpapers/RBOS_Desktop/contents/images/1920x1200.png

ffmpeg -i "$SCRIPTFOLDERPATH"/wallpaper_boot.png -i "$SCRIPTFOLDERPATH"/rbos_logo_boot.png -filter_complex "[1] unpremultiply=inplace=1 [front]; [0] [front] overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2:format=rgb" -map 0:a?  -y "$SCRIPTFOLDERPATH"/../../rebeccablackos_files/usr/share/wallpapers/RBOS_Bootsplash/contents/images/1920x1200.png
