#! /usr/bin/expect
#    Copyright (c) 2012, nerdopolis (or n3rdopolis) <bluescreen_avenger@version.net>
#
#    This file is part of RebeccaBlackLinux.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#using the password argument sent, put it into a variable
set LOGINUSER $::env(LOGINUSER)
set password [lindex $argv 0]

#test with /bin/true, before trying the real login so that the password fail result can be returned to the main script
su $LOGINUSER -c /bin/true
expect "Password:"

send "$password\r";

catch wait result
set status [lindex $result 3]

if { $status == 0 } {
set PID [spawn su $LOGINUSER -c /usr/bin/wlsessionmanager]
expect "Password:"

send "$password\r";

# TODO foward $PID the result somewhere
interact
} else {exit 1}
