#! /bin/sh
### BEGIN INIT INFO
# Provides:          remastersys-firstboot
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run firstboot items for remastersys after a remastered system has been installed
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
        #REM302
        if [ "`cat /proc/cmdline | grep casper`" = "" ]; then
            [ "$VERBOSE" != no ] && log_begin_msg "Running remastersys-firstboot"
            (sleep 60 && update-rc.d -f remastersys-firstboot remove) &
            sed -i -e 's/root:x:/root:!:/g' /etc/shadow
            rm -rf /home/*/Desktop/ubiquity*.desktop
	    groupadd weston-launch -r
	    usermod -a -G weston-launch $(cat /etc/passwd | grep :1000:1000: | awk -F : '{print $1}')

            #Place your custom commands below this line

            #Place your custom commands above this line
            ES=$?
            [ "$VERBOSE" != no ] && log_end_msg $ES
            return $ES
        fi

        


} 

case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

